# Generated by Django 4.2.2 on 2023-07-07 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{4}$', message='four-digit number')])),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{1,7}$)|(^None$)', message='Either None or up to 7 digits not starting with 0')])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{3,8}$)|(^None$)', message='3-8 digits, not starting with 0 and without char $')])),
                ('warranty', models.DateField()),
                ('weight', models.IntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{3,4}$)|(^None$)', message='3-4 digits, not starting with 0')])),
                ('accident', models.BooleanField(default=False)),
                ('car_owners', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{1,2}$)|(^None$)', message='1-2 digits, not starting with 0')])),
                ('to_100', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\.\\d{2}$', message='1-3 digits before dot and 2 digits after dot')])),
                ('engine', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^(V|I|F)[1-9]|1[0-6]$', message='V, I or F and number of cylinders (example: V8 or I4)')])),
                ('power', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[1-9]\\d{1,3}$', message='2-4 digits, not starting with 0')])),
                ('torque', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[1-9]\\d{1,3}$', message='2-4 digits, not starting with 0')])),
            ],
        ),
    ]
