# Generated by Django 4.2.2 on 2023-07-05 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_owners',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{1,2}$)|(^None$)', message='1-2 digits, not starting with 0')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{1,7}$)|(^None$)', message='Either None or up to 7 digits not starting with 0')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{3,8}$)|(^None$)', message='3-8 digits, not starting with 0 and without char $')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('(^(?!0)\\d{3,4}$)|(^None$)', message='3-4 digits, not starting with 0')]),
        ),
    ]
