export const countriesData = [
    { label: 'Australia', value: '+61' },
    { label: 'Austria', value: '+43' },
    { label: 'Azerbaijan', value: '+994' },
    { label: 'Albania', value: '+355' },
    { label: 'Algeria', value: '+213' },
    { label: 'Angola', value: '+244' },
    { label: 'Andorra', value: '+376' },
    { label: 'Antigua and Barbuda', value: '+1268' },
    { label: 'Argentina', value: '+54' },
    { label: 'Armenia', value: '+374' },
    { label: 'Afghanistan', value: '+93' },
    { label: 'Bahamas', value: '+1242' },
    { label: 'Bangladesh', value: '+880' },
    { label: 'Barbados', value: '+1246' },
    { label: 'Bahrain', value: '+973' },
    { label: 'Belarus', value: '+375' },
    { label: 'Belize', value: '+501' },
    { label: 'Belgium', value: '+32' },
    { label: 'Benin', value: '+229' },
    { label: 'Bulgaria', value: '+359' },
    { label: 'Bolivia', value: '+591' },
    { label: 'Bosnia and Herzegovina', value: '+387' },
    { label: 'Botswana', value: '+267' },
    { label: 'Brazil', value: '+55' },
    { label: 'Brunei', value: '+673' },
    { label: 'Burkina Faso', value: '+226' },
    { label: 'Burundi', value: '+257' },
    { label: 'Bhutan', value: '+975' },
    { label: 'Vanuatu', value: '+678' },
    { label: 'Vatican City', value: '+39' },
    { label: 'Great Britain', value: '+44' },
    { label: 'Hungary', value: '+36' },
    { label: 'Venezuela', value: '+58' },
    { label: 'East Timor', value: '+670' },
    { label: 'Vietnam', value: '+84' },
    { label: 'Gabon', value: '+241' },
    { label: 'Haiti', value: '+509' },
    { label: 'Guyana', value: '+592' },
    { label: 'Gambia', value: '+220' },
    { label: 'Ghana', value: '+233' },
    { label: 'Guatemala', value: '+502' },
    { label: 'Guinea', value: '+224' },
    { label: 'Guinea-Bissau', value: '+245' },
    { label: 'Germany', value: '+49' },
    { label: 'Honduras', value: '+504' },
    { label: 'Grenada', value: '+1473' },
    { label: 'Greece', value: '+30' },
    { label: 'Georgia', value: '+995' },
    { label: 'Denmark', value: '+45' },
    { label: 'Djibouti', value: '+253' },
    { label: 'Dominica', value: '+1767' },
    { label: 'Dominican Republic', value: '+1809' },
    { label: 'Egypt', value: '+20' },
    { label: 'Zambia', value: '+260' },
    { label: 'Zimbabwe', value: '+263' },
    { label: 'Israel', value: '+972' },
    { label: 'India', value: '+91' },
    { label: 'Indonesia', value: '+62' },
    { label: 'Jordan', value: '+962' },
    { label: 'Iraq', value: '+964' },
    { label: 'Iran', value: '+98' },
    { label: 'Ireland', value: '+353' },
    { label: 'Iceland', value: '+354' },
    { label: 'Spain', value: '+34' },
    { label: 'Italy', value: '+39' },
    { label: 'Yemen', value: '+967' },
    { label: 'Cape Verde', value: '+238' },
    { label: 'Kazakhstan', value: '+77' },
    { label: 'Cambodia', value: '+855' },
    { label: 'Cameroon', value: '+237' },
    { label: 'Canada', value: '+1' },
    { label: 'Qatar', value: '+974' },
    { label: 'Kenya', value: '+254' },
    { label: 'Cyprus', value: '+357' },
    { label: 'Kyrgyzstan', value: '+996' },
    { label: 'Kiribati', value: '+686' },
    { label: 'China', value: '+86' },
    { label: 'Colombia', value: '+57' },
    { label: 'Comoros', value: '+269' },
    { label: 'Congo, Democratic Republic', value: '+243' },
    { label: 'Congo, Republic', value: '+242' },
    { label: 'Costa Rica', value: '+506' },
    { label: 'Ivory Coast', value: '+225' },
    { label: 'Cuba', value: '+53' },
    { label: 'Kuwait', value: '+965' },
    { label: 'Laos', value: '+856' },
    { label: 'Latvia', value: '+371' },
    { label: 'Lesotho', value: '+266' },
    { label: 'Liberia', value: '+231' },
    { label: 'Lebanon', value: '+961' },
    { label: 'Libya', value: '+218' },
    { label: 'Lithuania', value: '+370' },
    { label: 'Liechtenstein', value: '+423' },
    { label: 'Luxembourg', value: '+352' },
    { label: 'Mauritius', value: '+230' },
    { label: 'Mauritania', value: '+222' },
    { label: 'Madagascar', value: '+261' },
    { label: 'Macedonia', value: '+389' },
    { label: 'Malawi', value: '+265' },
    { label: 'Malaysia', value: '+60' },
    { label: 'Mali', value: '+223' },
    { label: 'Maldives', value: '+960' },
    { label: 'Malta', value: '+356' },
    { label: 'Morocco', value: '+212' },
    { label: 'Marshall Islands', value: '+692' },
    { label: 'Mexico', value: '+52' },
    { label: 'Mozambique', value: '+259' },
    { label: 'Moldova', value: '+373' },
    { label: 'Monaco', value: '+377' },
    { label: 'Mongolia', value: '+976' },
    { label: 'Myanmar', value: '+95' },
    { label: 'Namibia', value: '+264' },
    { label: 'Nauru', value: '+674' },
    { label: 'Nepal', value: '+977' },
    { label: 'Niger', value: '+227' },
    { label: 'Nigeria', value: '+234' },
    { label: 'Netherlands', value: '+31' },
    { label: 'Nicaragua', value: '+505' },
    { label: 'New Zealand', value: '+64' },
    { label: 'Norway', value: '+47' },
    { label: 'United Arab Emirates', value: '+971' },
    { label: 'Oman', value: '+968' },
    { label: 'Pakistan', value: '+92' },
    { label: 'Palau', value: '+680' },
    { label: 'Panama', value: '+507' },
    { label: 'Papua New Guinea', value: '+675' },
    { label: 'Paraguay', value: '+595' },
    { label: 'Peru', value: '+51' },
    { label: 'Poland', value: '+48' },
    { label: 'Portugal', value: '+351' },
    { label: 'Russia', value: '+7' },
    { label: 'Rwanda', value: '+250' },
    { label: 'Romania', value: '+40' },
    { label: 'El Salvador', value: '+503' },
    { label: 'Samoa', value: '+685' },
    { label: 'San Marino', value: '+378' },
    { label: 'Sao Tome and Principe', value: '+239' },
    { label: 'Saudi Arabia', value: '+966' },
    { label: 'Swaziland', value: '+268' },
    { label: 'North Korea', value: '+850' },
    { label: 'Seychelles', value: '+248' },
    { label: 'Senegal', value: '+221' },
    { label: 'Saint Vincent and the Grenadines', value: '+1784' },
    { label: 'Saint Kitts and Nevis', value: '+1869' },
    { label: 'Saint Lucia', value: '+1758' },
    { label: 'Serbia', value: '+381' },
    { label: 'Singapore', value: '+65' },
    { label: 'Syria', value: '+963' },
    { label: 'Slovakia', value: '+421' },
    { label: 'Slovenia', value: '+986' },
    { label: 'United States of America', value: '+1' },
    { label: 'Solomon Islands', value: '+677' },
    { label: 'Somalia', value: '+252' },
    { label: 'Sudan', value: '+249' },
    { label: 'Surilabel', value: '+597' },
    { label: 'Sierra Leone', value: '+232' },
    { label: 'Tajikistan', value: '+992' },
    { label: 'Thailand', value: '+66' },
    { label: 'Tanzania', value: '+255' },
    { label: 'Togo', value: '+228' },
    { label: 'Tonga', value: '+676' },
    { label: 'Trinidad and Tobago', value: '+1868' },
    { label: 'Tuvalu', value: '+688' },
    { label: 'Tunisia', value: '+216' },
    { label: 'Turkmenistan', value: '+993' },
    { label: 'Turkey', value: '+90' },
    { label: 'Uganda', value: '+256' },
    { label: 'Uzbekistan', value: '+998' },
    { label: 'Ukraine', value: '+380' },
    { label: 'Uruguay', value: '+598' },
    { label: 'Federated States of Micronesia', value: '+691' },
    { label: 'Fiji', value: '+679' },
    { label: 'Philippines', value: '+63' },
    { label: 'Finland', value: '+358' },
    { label: 'France', value: '+33' },
    { label: 'Croatia', value: '+385' },
    { label: 'Central African Republic', value: '+236' },
    { label: 'Chad', value: '+235' },
    { label: 'Montenegro', value: '+381' },
    { label: 'Czech Republic', value: '+420' },
    { label: 'Chile', value: '+56' },
    { label: 'Switzerland', value: '+41' },
    { label: 'Sweden', value: '+46' },
    { label: 'Sri Lanka', value: '+94' },
    { label: 'Ecuador', value: '+593' },
    { label: 'Equatorial Guinea', value: '+240' },
    { label: 'Eritrea', value: '+291' },
    { label: 'Estonia', value: '+372' },
    { label: 'Ethiopia', value: '+251' },
    { label: 'South Korea', value: '+82' },
    { label: 'South Africa', value: '+27' },
    { label: 'Jamaica', value: '+1876' },
    { label: 'Japan', value: '+81' },
  ];